import React, { useState, useEffect } from 'react';
import { Patient } from '../types';
import { X, Save } from 'lucide-react';

interface PatientFormProps {
  initialData?: Patient | null;
  onSubmit: (patient: Patient) => void;
  onCancel: () => void;
}

export const PatientForm: React.FC<PatientFormProps> = ({ initialData, onSubmit, onCancel }) => {
  const [formData, setFormData] = useState<Patient>({
    id: '',
    name: '',
    dob: '',
    gender: 'Otro',
    bloodType: '',
    allergies: [],
    chronicConditions: [],
    contact: ''
  });

  const [allergiesInput, setAllergiesInput] = useState('');
  const [conditionsInput, setConditionsInput] = useState('');

  useEffect(() => {
    if (initialData) {
      setFormData(initialData);
      setAllergiesInput(initialData.allergies.join(', '));
      setConditionsInput(initialData.chronicConditions.join(', '));
    } else {
      // New patient: Empty ID (will be generated by DB)
      setFormData({
        id: '',
        name: '',
        dob: '',
        gender: 'Otro',
        bloodType: '',
        allergies: [],
        chronicConditions: [],
        contact: ''
      });
      setAllergiesInput('');
      setConditionsInput('');
    }
  }, [initialData]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const finalData = {
      ...formData,
      allergies: allergiesInput.split(',').map(s => s.trim()).filter(s => s !== ''),
      chronicConditions: conditionsInput.split(',').map(s => s.trim()).filter(s => s !== '')
    };
    onSubmit(finalData);
  };

  return (
    <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto animate-fade-in">
        <div className="p-6 border-b border-slate-200 flex justify-between items-center sticky top-0 bg-white z-10">
          <h2 className="text-2xl font-bold text-slate-800">
            {initialData ? 'Editar Paciente' : 'Registrar Nuevo Paciente'}
          </h2>
          <button onClick={onCancel} className="text-slate-400 hover:text-slate-600">
            <X size={24} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Nombre Completo</label>
              <input
                required
                type="text"
                className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                value={formData.name}
                onChange={e => setFormData({...formData, name: e.target.value})}
              />
            </div>
            {/* Show ID only if editing */}
            {initialData && (
                <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">ID Paciente</label>
                <input
                    required
                    type="text"
                    className="w-full p-2 border border-slate-300 rounded-lg bg-slate-50 text-slate-500 cursor-not-allowed"
                    value={formData.id}
                    readOnly
                />
                </div>
            )}
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Fecha de Nacimiento</label>
              <input
                required
                type="date"
                className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                value={formData.dob}
                onChange={e => setFormData({...formData, dob: e.target.value})}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Género</label>
              <select
                className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                value={formData.gender}
                onChange={e => setFormData({...formData, gender: e.target.value as any})}
              >
                <option value="Masculino">Masculino</option>
                <option value="Femenino">Femenino</option>
                <option value="Otro">Otro</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Tipo de Sangre</label>
              <select
                className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                value={formData.bloodType}
                onChange={e => setFormData({...formData, bloodType: e.target.value})}
              >
                <option value="">Seleccionar</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Teléfono de Contacto</label>
              <input
                required
                type="tel"
                className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                value={formData.contact}
                onChange={e => setFormData({...formData, contact: e.target.value})}
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Alergias (separadas por coma)</label>
            <textarea
              className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              rows={2}
              placeholder="Ej: Penicilina, Polvo, Nueces"
              value={allergiesInput}
              onChange={e => setAllergiesInput(e.target.value)}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Enfermedades Crónicas (separadas por coma)</label>
            <textarea
              className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"
              rows={2}
              placeholder="Ej: Diabetes Tipo 2, Hipertensión"
              value={conditionsInput}
              onChange={e => setConditionsInput(e.target.value)}
            />
          </div>

          <div className="pt-4 flex justify-end space-x-3">
            <button
              type="button"
              onClick={onCancel}
              className="px-4 py-2 text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg font-medium transition-colors"
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="px-4 py-2 text-white bg-blue-600 hover:bg-blue-700 rounded-lg font-medium transition-colors flex items-center"
            >
              <Save size={18} className="mr-2" />
              Guardar Paciente
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};